[project]
name = "teo-chat-piano"
version = "0.1.0"
description = "For demo with Teo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "dotenv>=0.9.9",
    "mido>=1.3.3",
    "openai>=1.92.3",
    "tqdm>=4.67.1",
]
